version: "3"

services:
  Test-project-creation-api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "8080:8080"
  Test-project-creation-ui:
    build:
      context: apps/ui
      args:
        APP_SERVER_HOST: localhost
        APP_SERVER_PORT: 8080
    ports:
      - "80:80"
    depends_on:
      - Test-project-creation-api
    links:
      - Test-project-creation-api
